# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 108 code points in Unicode Version 6.0.0 that match
# any of the following regular expression constructs:
# 
#         \p{Script=Brahmi}
#         \p{Sc=Brah}
#         \p{Is_Script=Brahmi}
#         \p{Is_Sc=Brah}
# 
#         \p{Brahmi}
#         \p{Is_Brahmi}
#         \p{Brah}
#         \p{Is_Brah}
# 
#     Note that contrary to what you might expect, the above is NOT the same
#     as \p{Block=Brahmi}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Sc: Brahmi}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
11000	1104D	# [78]
11052	1106F	# [30]
END
