# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 6379 code points in Unicode Version 6.0.0 that match
# any of the following regular expression constructs:
# 
#         \p{Script=Common}
#         \p{Sc=Zyyy}
#         \p{Is_Script=Common}
#         \p{Is_Sc=Zyyy}
# 
#         \p{Common}
#         \p{Is_Common}
#         \p{Zyyy}
#         \p{Is_Zyyy}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Sc: Common}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
0000	0040	# [65]
005B	0060	# [6]
007B	00A9	# [47]
00AB	00B9	# [15]
00BB	00BF	# [5]
00D7		
00F7		
02B9	02DF	# [39]
02E5	02E9	# [5]
02EC	02FF	# [20]
0374		
037E		
0385		
0387		
0589		
060C		
061B		
061F		
0640		
0660	0669	# [10]
06DD		
0964	0965	# [2]
0970		
0E3F		
0FD5	0FD8	# [4]
10FB		
16EB	16ED	# [3]
1735	1736	# [2]
1802	1803	# [2]
1805		
1CD3		
1CE1		
1CE9	1CEC	# [4]
1CEE	1CF2	# [5]
2000	200B	# [12]
200E	2064	# [87]
206A	2070	# [7]
2074	207E	# [11]
2080	208E	# [15]
20A0	20B9	# [26]
2100	2125	# [38]
2127	2129	# [3]
212C	2131	# [6]
2133	214D	# [27]
214F	215F	# [17]
2189		
2190	23F3	# [612]
2400	2426	# [39]
2440	244A	# [11]
2460	26FF	# [672]
2701	27CA	# [202]
27CC		
27CE	27FF	# [50]
2900	2B4C	# [589]
2B50	2B59	# [10]
2E00	2E31	# [50]
2FF0	2FFB	# [12]
3000	3004	# [5]
3006		
3008	3020	# [25]
3030	3037	# [8]
303C	303F	# [4]
309B	309C	# [2]
30A0		
30FB	30FC	# [2]
3190	319F	# [16]
31C0	31E3	# [36]
3220	325F	# [64]
327F	32CF	# [81]
3358	33FF	# [168]
4DC0	4DFF	# [64]
A700	A721	# [34]
A788	A78A	# [3]
A830	A839	# [10]
FD3E	FD3F	# [2]
FDFD		
FE10	FE19	# [10]
FE30	FE52	# [35]
FE54	FE66	# [19]
FE68	FE6B	# [4]
FEFF		
FF01	FF20	# [32]
FF3B	FF40	# [6]
FF5B	FF65	# [11]
FF70		
FF9E	FF9F	# [2]
FFE0	FFE6	# [7]
FFE8	FFEE	# [7]
FFF9	FFFD	# [5]
10100	10102	# [3]
10107	10133	# [45]
10137	1013F	# [9]
10190	1019B	# [12]
101D0	101FC	# [45]
1D000	1D0F5	# [246]
1D100	1D126	# [39]
1D129	1D166	# [62]
1D16A	1D17A	# [17]
1D183	1D184	# [2]
1D18C	1D1A9	# [30]
1D1AE	1D1DD	# [48]
1D300	1D356	# [87]
1D360	1D371	# [18]
1D400	1D454	# [85]
1D456	1D49C	# [71]
1D49E	1D49F	# [2]
1D4A2		
1D4A5	1D4A6	# [2]
1D4A9	1D4AC	# [4]
1D4AE	1D4B9	# [12]
1D4BB		
1D4BD	1D4C3	# [7]
1D4C5	1D505	# [65]
1D507	1D50A	# [4]
1D50D	1D514	# [8]
1D516	1D51C	# [7]
1D51E	1D539	# [28]
1D53B	1D53E	# [4]
1D540	1D544	# [5]
1D546		
1D54A	1D550	# [7]
1D552	1D6A5	# [340]
1D6A8	1D7CB	# [292]
1D7CE	1D7FF	# [50]
1F000	1F02B	# [44]
1F030	1F093	# [100]
1F0A0	1F0AE	# [15]
1F0B1	1F0BE	# [14]
1F0C1	1F0CF	# [15]
1F0D1	1F0DF	# [15]
1F100	1F10A	# [11]
1F110	1F12E	# [31]
1F130	1F169	# [58]
1F170	1F19A	# [43]
1F1E6	1F1FF	# [26]
1F201	1F202	# [2]
1F210	1F23A	# [43]
1F240	1F248	# [9]
1F250	1F251	# [2]
1F300	1F320	# [33]
1F330	1F335	# [6]
1F337	1F37C	# [70]
1F380	1F393	# [20]
1F3A0	1F3C4	# [37]
1F3C6	1F3CA	# [5]
1F3E0	1F3F0	# [17]
1F400	1F43E	# [63]
1F440		
1F442	1F4F7	# [182]
1F4F9	1F4FC	# [4]
1F500	1F53D	# [62]
1F550	1F567	# [24]
1F5FB	1F5FF	# [5]
1F601	1F610	# [16]
1F612	1F614	# [3]
1F616		
1F618		
1F61A		
1F61C	1F61E	# [3]
1F620	1F625	# [6]
1F628	1F62B	# [4]
1F62D		
1F630	1F633	# [4]
1F635	1F640	# [12]
1F645	1F64F	# [11]
1F680	1F6C5	# [70]
1F700	1F773	# [116]
E0001		
E0020	E007F	# [96]
END
