#!/bin/env perl

use v5.14;    # or later

run(@ARGV) unless caller;

sub run {
    my (@args) = @_;

    my @tests;
    while ( $args[-1] && $args[-1] =~ m/\.t$/ ) {
        my $t = pop @args;
        die "Need a CORE/*.t file as last argument" unless $t && $t =~ qr{t/CORE/.*\.t$};

        my ( $before, $after ) = split( '/CORE/', $t );
        $after =~ s{/}{--}g;
        $t = $before . '/C-COMPILED/CORE--' . $after;

        if ( !-e $t ) {
            $t =~ s{\.t$}{==*.t};
            $t = ( glob $t )[0];
        }

        die "Cannot find a test file" unless -e $t;
        unshift @tests, $t;
    }

    my @cmd = ( 'prove', @args, @tests );
    say "Running: ", join( ' ', @cmd );

    exec(@cmd);

    return 0;
}
