#!/bin/env perl

my $cfile = shift or die "need a c file";
my $tidy = "$cfile.tdy";

$cfile =~ qr{\.c$} or do {
	my $new = $cfile . q{.c};
	qx{cp $cfile $new};
	$cfile = $new;
};

my @cmd = (
    qq{gcc -fpreprocessed -dD -E $cfile > $tidy.tmp},
    qq{indent -bap $tidy.tmp},
    qq{grep '[^[:blank:]]' < $tidy.tmp > $tidy}
);

foreach my $exe (@cmd) {
    print "> $exe\n";
    qx{$exe};
    die "exit with error code $?: $exe" unless $? == 0;
}
print "Done: $tidy\n";
exit;
