#!/bin/sh
arch="$(uname -s)"
perlall=${perlall:-"5.6.2 5.8.9d 5.8.9d-nt 5.10.0-nt 5.10.1 5.11.5-nt 5.12.0 5.12.1d-nt 5.13.5-nt 5.13.5 5.13.5d 5.13.5d-nt"}
# may link to perlall-make and perlall-makeinstall
base=$(basename $0)

test -e Makefile.PL || exit 1
test -d blib && rm -rf blib && test -e lib/B/Asmdata.pm && rm lib/B/Asmdata.pm

for p in $perlall
do 
  log="log.test-$arch-$p"
  rm $log 2>/dev/null
  make -s clean
  if [ -d .svn ]; then
      echo $(svn info|grep Revision) >$log
      echo $(svn status t/*.t t/*.pm lib/B/C*.pm) >>$log
  fi
  echo perl$p Makefile.PL
  perl$p Makefile.PL 2>&1 >>$log && \
  ( make 2>&1 >>$log && \
    if [ "$base" = "perlall-maketest" ]; then
	make test TEST_VERBOSE=1 2>&1 | tee -a $log
    fi
    if [ $? = 0 -a "$base" = "perlall-makeinstall" ]
    then
	make test install 2>&1 | tee -a $log 
    fi
    ( echo >> $log
      echo "----" >> $log
      echo >> $log
      perl$p -V >> log.test-$arch-$p) )
  #make -s clean
done
