#!/bin/bash
# ./store_rpt mv -v 1.34
function do_cp {
    for r in $r
      do 
      for f in $(grep -l "$grep$r" $m)
      do 
        mkdir -p t/reports/$v/r$r
	if test "$move" = "1"
	then
	    mv $f t/reports/$v/r$r/
	else
	    cp -p $f t/reports/$v/r$r/
	fi
      done
    done
}

if test "$1" = "mv"; then move=1; shift; fi
if test "$1" = "-v"; then v=$2; fi
v=${1:-1.36}

m=$(ls log.modules-5.*|egrep -v ".(orig|err)")
if [ -n "$m" ]; then
    grep="VERSION = $v r"
    r=$(perl -lane "print substr(\$F[4],1) if /VERSION = $v r/" $m)
    do_cp
fi

m=$(ls log.test-*-5.*|egrep -v ".(orig|err)")
if [ -n "$m" ]; then
    grep="Revision: "
    r=$(perl -lane "print \$F[1] if /^Revision: \\d+\$/" $m)
    do_cp
fi
