#!/bin/bash
function do_cp {
    for r in $r
      do 
      for f in $(grep -l "$grep$r" $m)
        do 
        mkdir -p t/reports/1.32/r$r; cp -p $f t/reports/1.32/r$r/
      done
    done
}
function do_mv {
    for r in $r
      do 
      for f in $(grep -l "$grep$r" $m)
        do 
        mkdir -p t/reports/1.32/r$r; mv $f t/reports/1.32/r$r/
      done
    done
}

v=${1:-1.32}

m=$(ls log.modules-5.*|egrep -v ".(orig|err)")
grep="VERSION = $v r"
r=$(perl -lane "print substr(\$F[4],1) if /VERSION = $v r/" $m|sort -u)
#do_mv
do_cp

m=$(ls log.test-*-5.*|egrep -v ".(orig|err)")
grep="Revision: "
r=$(perl -lane "print \$F[1] if /^Revision: \\d+\$/" $m|sort -u)

#do_mv
do_cp
