# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 2088 code points in Unicode Version 6.0.0 that match
# any of the following regular expression constructs:
# 
#         \p{Age=6.0}
#         \p{Is_Age=6.0}
# 
#     Meaning: Code point's usage was introduced in version 6.0
# 
#     Note: See also Property 'Present_In'
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Age: 6.0}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
0526	0527	# [2]
0620		
065F		
0840	085B	# [28]
085E		
093A	093B	# [2]
094F		
0956	0957	# [2]
0973	0977	# [5]
0B72	0B77	# [6]
0D29		
0D3A		
0D4E		
0F8C	0F8F	# [4]
0FD9	0FDA	# [2]
135D	135E	# [2]
1BC0	1BF3	# [52]
1BFC	1BFF	# [4]
1DFC		
2095	209C	# [8]
20B9		
23E9	23F3	# [11]
26CE		
26E2		
26E4	26E7	# [4]
2705		
270A	270B	# [2]
2728		
274C		
274E		
2753	2755	# [3]
275F	2760	# [2]
2795	2797	# [3]
27B0		
27BF		
27CE	27CF	# [2]
2D70		
2D7F		
31B8	31BA	# [3]
A660	A661	# [2]
A78D	A78E	# [2]
A790	A791	# [2]
A7A0	A7A9	# [10]
A7FA		
AB01	AB06	# [6]
AB09	AB0E	# [6]
AB11	AB16	# [6]
AB20	AB26	# [7]
AB28	AB2E	# [7]
FBB2	FBC1	# [16]
11000	1104D	# [78]
11052	1106F	# [30]
16800	16A38	# [569]
1B000	1B001	# [2]
1F0A0	1F0AE	# [15]
1F0B1	1F0BE	# [14]
1F0C1	1F0CF	# [15]
1F0D1	1F0DF	# [15]
1F130		
1F132	1F13C	# [11]
1F13E		
1F140	1F141	# [2]
1F143	1F145	# [3]
1F147	1F149	# [3]
1F14F	1F156	# [8]
1F158	1F15E	# [7]
1F160	1F169	# [10]
1F170	1F178	# [9]
1F17A		
1F17D	1F17E	# [2]
1F180	1F189	# [10]
1F18E	1F18F	# [2]
1F191	1F19A	# [10]
1F1E6	1F1FF	# [26]
1F201	1F202	# [2]
1F232	1F23A	# [9]
1F250	1F251	# [2]
1F300	1F320	# [33]
1F330	1F335	# [6]
1F337	1F37C	# [70]
1F380	1F393	# [20]
1F3A0	1F3C4	# [37]
1F3C6	1F3CA	# [5]
1F3E0	1F3F0	# [17]
1F400	1F43E	# [63]
1F440		
1F442	1F4F7	# [182]
1F4F9	1F4FC	# [4]
1F500	1F53D	# [62]
1F550	1F567	# [24]
1F5FB	1F5FF	# [5]
1F601	1F610	# [16]
1F612	1F614	# [3]
1F616		
1F618		
1F61A		
1F61C	1F61E	# [3]
1F620	1F625	# [6]
1F628	1F62B	# [4]
1F62D		
1F630	1F633	# [4]
1F635	1F640	# [12]
1F645	1F64F	# [11]
1F680	1F6C5	# [70]
1F700	1F773	# [116]
2B740	2B81D	# [222]
END
