# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 4398 code points in Unicode Version 6.0.0 that match
# any of the following regular expression constructs:
# 
#         \p{General_Category=Other_Symbol}
#         \p{Gc=So}
#         \p{Category=Other_Symbol}
#         \p{Is_General_Category=So}
#         \p{Is_Gc=Other_Symbol}
#         \p{Is_Category=So}
# 
#         \p{Other_Symbol}
#         \p{Is_Other_Symbol}
#         \p{So}
#         \p{Is_So}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Category: Other_Symbol}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
00A6	00A7	# [2]
00A9		
00AE		
00B0		
00B6		
0482		
060E	060F	# [2]
06DE		
06E9		
06FD	06FE	# [2]
07F6		
09FA		
0B70		
0BF3	0BF8	# [6]
0BFA		
0C7F		
0D79		
0F01	0F03	# [3]
0F13	0F17	# [5]
0F1A	0F1F	# [6]
0F34		
0F36		
0F38		
0FBE	0FC5	# [8]
0FC7	0FCC	# [6]
0FCE	0FCF	# [2]
0FD5	0FD8	# [4]
109E	109F	# [2]
1360		
1390	1399	# [10]
1940		
19DE	19FF	# [34]
1B61	1B6A	# [10]
1B74	1B7C	# [9]
2100	2101	# [2]
2103	2106	# [4]
2108	2109	# [2]
2114		
2116	2117	# [2]
211E	2123	# [6]
2125		
2127		
2129		
212E		
213A	213B	# [2]
214A		
214C	214D	# [2]
214F		
2195	2199	# [5]
219C	219F	# [4]
21A1	21A2	# [2]
21A4	21A5	# [2]
21A7	21AD	# [7]
21AF	21CD	# [31]
21D0	21D1	# [2]
21D3		
21D5	21F3	# [31]
2300	2307	# [8]
230C	231F	# [20]
2322	2328	# [7]
232B	237B	# [81]
237D	239A	# [30]
23B4	23DB	# [40]
23E2	23F3	# [18]
2400	2426	# [39]
2440	244A	# [11]
249C	24E9	# [78]
2500	25B6	# [183]
25B8	25C0	# [9]
25C2	25F7	# [54]
2600	266E	# [111]
2670	26FF	# [144]
2701	2767	# [103]
2794	27BF	# [44]
2800	28FF	# [256]
2B00	2B2F	# [48]
2B45	2B46	# [2]
2B50	2B59	# [10]
2CE5	2CEA	# [6]
2E80	2E99	# [26]
2E9B	2EF3	# [89]
2F00	2FD5	# [214]
2FF0	2FFB	# [12]
3004		
3012	3013	# [2]
3020		
3036	3037	# [2]
303E	303F	# [2]
3190	3191	# [2]
3196	319F	# [10]
31C0	31E3	# [36]
3200	321E	# [31]
322A	3250	# [39]
3260	327F	# [32]
328A	32B0	# [39]
32C0	32FE	# [63]
3300	33FF	# [256]
4DC0	4DFF	# [64]
A490	A4C6	# [55]
A828	A82B	# [4]
A836	A837	# [2]
A839		
AA77	AA79	# [3]
FDFD		
FFE4		
FFE8		
FFED	FFEE	# [2]
FFFC	FFFD	# [2]
10102		
10137	1013F	# [9]
10179	10189	# [17]
10190	1019B	# [12]
101D0	101FC	# [45]
1D000	1D0F5	# [246]
1D100	1D126	# [39]
1D129	1D164	# [60]
1D16A	1D16C	# [3]
1D183	1D184	# [2]
1D18C	1D1A9	# [30]
1D1AE	1D1DD	# [48]
1D200	1D241	# [66]
1D245		
1D300	1D356	# [87]
1F000	1F02B	# [44]
1F030	1F093	# [100]
1F0A0	1F0AE	# [15]
1F0B1	1F0BE	# [14]
1F0C1	1F0CF	# [15]
1F0D1	1F0DF	# [15]
1F110	1F12E	# [31]
1F130	1F169	# [58]
1F170	1F19A	# [43]
1F1E6	1F202	# [29]
1F210	1F23A	# [43]
1F240	1F248	# [9]
1F250	1F251	# [2]
1F300	1F320	# [33]
1F330	1F335	# [6]
1F337	1F37C	# [70]
1F380	1F393	# [20]
1F3A0	1F3C4	# [37]
1F3C6	1F3CA	# [5]
1F3E0	1F3F0	# [17]
1F400	1F43E	# [63]
1F440		
1F442	1F4F7	# [182]
1F4F9	1F4FC	# [4]
1F500	1F53D	# [62]
1F550	1F567	# [24]
1F5FB	1F5FF	# [5]
1F601	1F610	# [16]
1F612	1F614	# [3]
1F616		
1F618		
1F61A		
1F61C	1F61E	# [3]
1F620	1F625	# [6]
1F628	1F62B	# [4]
1F62D		
1F630	1F633	# [4]
1F635	1F640	# [12]
1F645	1F64F	# [11]
1F680	1F6C5	# [70]
1F700	1F773	# [116]
END
