/* -*- buffer-read-only: t -*-
 *
 *      Copyright (c) 1996-1999 Malcolm Beattie
 *      Copyright (c) 2008 Reini Urban
 *
 *      You may distribute under the terms of either the GNU General Public
 *      License or the Artistic License, as specified in the README file.
 *
 */
/*
 * This file is autogenerated from bytecode.pl. Changes made here will be lost.
 */

#define PERL_NO_GET_CONTEXT
#include "EXTERN.h"
#include "perl.h"
#define NO_XSLOCKS
#include "XSUB.h"

#ifndef PL_tokenbuf /* Change 31252: move PL_tokenbuf into the PL_parser struct */
#define PL_tokenbuf		(PL_parser->tokenbuf)
#endif

#include "byterun.h"
#include "bytecode.h"

static const int optype_size[] = {
    sizeof(OP),
    sizeof(UNOP),
    sizeof(BINOP),
    sizeof(LOGOP),
    sizeof(LISTOP),
    sizeof(PMOP),
    sizeof(SVOP),
    sizeof(PADOP),
    sizeof(PVOP),
    sizeof(LOOP),
    sizeof(COP)
};

void *
bset_obj_store(pTHX_ struct byteloader_state *bstate, void *obj, I32 ix)
{
    if (ix > bstate->bs_obj_list_fill) {
	Renew(bstate->bs_obj_list, ix + 32, void*);
	bstate->bs_obj_list_fill = ix + 31;
    }
    bstate->bs_obj_list[ix] = obj;
    return obj;
}

int
byterun(pTHX_ struct byteloader_state *bstate)
{
    register int insn;
    U32 isjit = 0;
    U32 ix;
    SV *specialsv_list[7];

    BYTECODE_HEADER_CHECK;	/* croak if incorrect platform, set isjit if PLJC magic header */
    if (isjit) {
        return jitrun(aTHX_ &bstate);
    } else {
        Newx(bstate->bs_obj_list, 32, void*); /* set op objlist */
        bstate->bs_obj_list_fill = 31;
        bstate->bs_obj_list[0] = NULL; /* first is always Null */
        bstate->bs_ix = 1;
	DEBUG_l( Perl_deb(aTHX_ "(bstate.bs_fdata.idx %d)\n", bstate->bs_fdata->idx));
	DEBUG_l( Perl_deb(aTHX_ "(bstate.bs_fdata.next_out %d)\n", bstate->bs_fdata->next_out));
	DEBUG_l( Perl_deb(aTHX_ "(bstate.bs_fdata.datasv %p:\"%s\")\n", bstate->bs_fdata->datasv,
				 SvPV_nolen(bstate->bs_fdata->datasv)));

        specialsv_list[0] = Nullsv;
        specialsv_list[1] = &PL_sv_undef;
        specialsv_list[2] = &PL_sv_yes;
        specialsv_list[3] = &PL_sv_no;
        specialsv_list[4] = (SV*)pWARN_ALL;
        specialsv_list[5] = (SV*)pWARN_NONE;
        specialsv_list[6] = (SV*)pWARN_STD;

        while ((insn = BGET_FGETC()) != EOF) {
	  DEBUG_l( Perl_deb(aTHX_ "(insn %d)\n", insn));
	  switch (insn) {
	  case INSN_COMMENT:		/* 35 */
	    {
		comment_t arg;
		BGET_comment_t(arg);
		arg = arg;
		break;
	    }
	  case INSN_NOP:		/* 10 */
	    {
		break;
	    }
	  case INSN_RET:		/* 0 */
	    {
		BSET_ret(none);
		break;
	    }
	  case INSN_LDSV:		/* 1 */
	    {
		svindex arg;
		BGET_svindex(arg);
		bstate->bs_sv = arg;
		break;
	    }
	  case INSN_LDOP:		/* 2 */
	    {
		opindex arg;
		BGET_opindex(arg);
		PL_op = arg;
		break;
	    }
	  case INSN_STSV:		/* 3 */
	    {
		U32 arg;
		BGET_U32(arg);
		BSET_OBJ_STORE(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_STOP:		/* 4 */
	    {
		U32 arg;
		BGET_U32(arg);
		BSET_OBJ_STORE(PL_op, arg);
		break;
	    }
	  case INSN_STPV:		/* 5 */
	    {
		U32 arg;
		BGET_U32(arg);
		BSET_stpv(BSTATE_xpv_pv, arg);
		break;
	    }
	  case INSN_LDSPECSV:		/* 6 */
	    {
		U8 arg;
		BGET_U8(arg);
		BSET_ldspecsv(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_LDSPECSVX:		/* 7 */
	    {
		U8 arg;
		BGET_U8(arg);
		BSET_ldspecsvx(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_NEWSV:		/* 8 */
	    {
		U8 arg;
		BGET_U8(arg);
		BSET_newsv(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_NEWSVX:		/* 9 */
	    {
		U32 arg;
		BGET_U32(arg);
		BSET_newsvx(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_NEWOP:		/* 11 */
	    {
		U8 arg;
		BGET_U8(arg);
		BSET_newop(PL_op, arg);
		break;
	    }
	  case INSN_NEWOPX:		/* 12 */
	    {
		U16 arg;
		BGET_U16(arg);
		BSET_newopx(PL_op, arg);
		break;
	    }
	  case INSN_NEWOPN:		/* 13 */
	    {
		U8 arg;
		BGET_U8(arg);
		BSET_newopn(PL_op, arg);
		break;
	    }
	  case INSN_NEWPV:		/* 14 */
	    {
		PV arg;
		BGET_PV(arg);
		break;
	    }
	  case INSN_PV_CUR:		/* 15 */
	    {
		STRLEN arg;
		BGET_PADOFFSET(arg);
		bstate->bs_pv.xpv_cur = arg;
		break;
	    }
	  case INSN_PV_FREE:		/* 16 */
	    {
		BSET_pv_free(BSTATE_xpv_pv);
		break;
	    }
	  case INSN_SV_UPGRADE:		/* 17 */
	    {
		U8 arg;
		BGET_U8(arg);
		BSET_sv_upgrade(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_SV_REFCNT:		/* 18 */
	    {
		U32 arg;
		BGET_U32(arg);
		SvREFCNT(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_SV_REFCNT_ADD:		/* 19 */
	    {
		I32 arg;
		BGET_I32(arg);
		BSET_sv_refcnt_add(SvREFCNT(bstate->bs_sv), arg);
		break;
	    }
	  case INSN_SV_FLAGS:		/* 20 */
	    {
		U32 arg;
		BGET_U32(arg);
		SvFLAGS(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XRV:		/* 21 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_xrv(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_XPV:		/* 22 */
	    {
		BSET_xpv(bstate->bs_sv);
		break;
	    }
	  case INSN_XPV_CUR:		/* 23 */
	    {
		STRLEN arg;
		BGET_PADOFFSET(arg);
		BSET_xpv_cur(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_XPV_LEN:		/* 24 */
	    {
		STRLEN arg;
		BGET_PADOFFSET(arg);
		BSET_xpv_len(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_XIV:		/* 25 */
	    {
		IV arg;
		BGET_IV(arg);
		BSET_xiv(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_XNV:		/* 26 */
	    {
		NV arg;
		BGET_NV(arg);
		BSET_xnv(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_XLV_TARGOFF:		/* 27 */
	    {
		STRLEN arg;
		BGET_PADOFFSET(arg);
		LvTARGOFF(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XLV_TARGLEN:		/* 28 */
	    {
		STRLEN arg;
		BGET_PADOFFSET(arg);
		LvTARGLEN(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XLV_TARG:		/* 29 */
	    {
		svindex arg;
		BGET_svindex(arg);
		LvTARG(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XLV_TYPE:		/* 30 */
	    {
		char arg;
		BGET_U8(arg);
		LvTYPE(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XBM_USEFUL:		/* 31 */
	    {
		I32 arg;
		BGET_I32(arg);
		BmUSEFUL(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XBM_PREVIOUS:		/* 32 */
	    {
		U16 arg;
		BGET_U16(arg);
		BmPREVIOUS(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XBM_RARE:		/* 33 */
	    {
		U8 arg;
		BGET_U8(arg);
		BmRARE(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XFM_LINES:		/* 34 */
	    {
		IV arg;
		BGET_IV(arg);
		FmLINES(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_LINES:		/* 36 */
	    {
		IV arg;
		BGET_IV(arg);
		IoLINES(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_PAGE:		/* 37 */
	    {
		IV arg;
		BGET_IV(arg);
		IoPAGE(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_PAGE_LEN:		/* 38 */
	    {
		IV arg;
		BGET_IV(arg);
		IoPAGE_LEN(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_LINES_LEFT:		/* 39 */
	    {
		IV arg;
		BGET_IV(arg);
		IoLINES_LEFT(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_TOP_NAME:		/* 40 */
	    {
		pvindex arg;
		BGET_pvindex(arg);
		IoTOP_NAME(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_TOP_GV:		/* 41 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&IoTOP_GV(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_FMT_NAME:		/* 42 */
	    {
		pvindex arg;
		BGET_pvindex(arg);
		IoFMT_NAME(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_FMT_GV:		/* 43 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&IoFMT_GV(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_BOTTOM_NAME:		/* 44 */
	    {
		pvindex arg;
		BGET_pvindex(arg);
		IoBOTTOM_NAME(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_BOTTOM_GV:		/* 45 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&IoBOTTOM_GV(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_TYPE:		/* 46 */
	    {
		char arg;
		BGET_U8(arg);
		IoTYPE(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XIO_FLAGS:		/* 47 */
	    {
		char arg;
		BGET_U8(arg);
		IoFLAGS(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_XSUBANY:		/* 48 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&CvXSUBANY(bstate->bs_sv).any_ptr = arg;
		break;
	    }
	  case INSN_XCV_STASH:		/* 49 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&CvSTASH(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_START:		/* 50 */
	    {
		opindex arg;
		BGET_opindex(arg);
		CvSTART(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_ROOT:		/* 51 */
	    {
		opindex arg;
		BGET_opindex(arg);
		CvROOT(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_GV:		/* 52 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&CvGV(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_FILE:		/* 53 */
	    {
		pvindex arg;
		BGET_pvindex(arg);
		CvFILE(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_DEPTH:		/* 54 */
	    {
		long arg;
		BGET_long(arg);
		CvDEPTH(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_PADLIST:		/* 55 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&CvPADLIST(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_OUTSIDE:		/* 56 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&CvOUTSIDE(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_OUTSIDE_SEQ:		/* 57 */
	    {
		U32 arg;
		BGET_U32(arg);
		CvOUTSIDE_SEQ(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XCV_FLAGS:		/* 58 */
	    {
		U16 arg;
		BGET_U16(arg);
		CvFLAGS(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_AV_EXTEND:		/* 59 */
	    {
		SSize_t arg;
		BGET_PADOFFSET(arg);
		BSET_av_extend(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_AV_PUSHX:		/* 60 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_av_pushx(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_AV_PUSH:		/* 61 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_av_push(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_XAV_FILL:		/* 62 */
	    {
		SSize_t arg;
		BGET_PADOFFSET(arg);
		AvFILLp(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XAV_MAX:		/* 63 */
	    {
		SSize_t arg;
		BGET_PADOFFSET(arg);
		AvMAX(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_XAV_FLAGS:		/* 64 */
	    {
		I32 arg;
		BGET_I32(arg);
		((XPVAV*)(SvANY(bstate->bs_sv)))->xiv_u.xivu_i32 = arg;
		break;
	    }
	  case INSN_XHV_NAME:		/* 65 */
	    {
		pvindex arg;
		BGET_pvindex(arg);
		BSET_xhv_name(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_HV_STORE:		/* 66 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_hv_store(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_SV_MAGIC:		/* 67 */
	    {
		char arg;
		BGET_U8(arg);
		BSET_sv_magic(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_MG_OBJ:		/* 68 */
	    {
		svindex arg;
		BGET_svindex(arg);
		SvMAGIC(bstate->bs_sv)->mg_obj = arg;
		break;
	    }
	  case INSN_MG_PRIVATE:		/* 69 */
	    {
		U16 arg;
		BGET_U16(arg);
		SvMAGIC(bstate->bs_sv)->mg_private = arg;
		break;
	    }
	  case INSN_MG_FLAGS:		/* 70 */
	    {
		U8 arg;
		BGET_U8(arg);
		SvMAGIC(bstate->bs_sv)->mg_flags = arg;
		break;
	    }
	  case INSN_MG_NAME:		/* 71 */
	    {
		pvcontents arg;
		BGET_pvcontents(arg);
		BSET_mg_name(SvMAGIC(bstate->bs_sv), arg);
		break;
	    }
	  case INSN_MG_NAMEX:		/* 72 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_mg_namex(SvMAGIC(bstate->bs_sv), arg);
		break;
	    }
	  case INSN_XMG_STASH:		/* 73 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_xmg_stash(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_GV_FETCHPV:		/* 74 */
	    {
		strconst arg;
		BGET_strconst(arg);
		BSET_gv_fetchpv(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_GV_FETCHPVX:		/* 75 */
	    {
		strconst arg;
		BGET_strconst(arg);
		BSET_gv_fetchpvx(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_GV_STASHPV:		/* 76 */
	    {
		strconst arg;
		BGET_strconst(arg);
		BSET_gv_stashpv(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_GV_STASHPVX:		/* 77 */
	    {
		strconst arg;
		BGET_strconst(arg);
		BSET_gv_stashpvx(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_GP_SV:		/* 78 */
	    {
		svindex arg;
		BGET_svindex(arg);
		GvSV(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_REFCNT:		/* 79 */
	    {
		U32 arg;
		BGET_U32(arg);
		GvREFCNT(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_REFCNT_ADD:		/* 80 */
	    {
		I32 arg;
		BGET_I32(arg);
		BSET_gp_refcnt_add(GvREFCNT(bstate->bs_sv), arg);
		break;
	    }
	  case INSN_GP_AV:		/* 81 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&GvAV(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_HV:		/* 82 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&GvHV(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_CV:		/* 83 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&GvCV(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_FILE:		/* 84 */
	    {
		hekindex arg;
		BGET_hekindex(arg);
		GvFILE_HEK(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_IO:		/* 85 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&GvIOp(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_FORM:		/* 86 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&GvFORM(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_CVGEN:		/* 87 */
	    {
		U32 arg;
		BGET_U32(arg);
		GvCVGEN(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_LINE:		/* 88 */
	    {
		line_t arg;
		BGET_U32(arg);
		GvLINE(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_GP_SHARE:		/* 89 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_gp_share(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_XGV_FLAGS:		/* 90 */
	    {
		U8 arg;
		BGET_U8(arg);
		GvFLAGS(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_OP_NEXT:		/* 91 */
	    {
		opindex arg;
		BGET_opindex(arg);
		PL_op->op_next = arg;
		break;
	    }
	  case INSN_OP_SIBLING:		/* 92 */
	    {
		opindex arg;
		BGET_opindex(arg);
		PL_op->op_sibling = arg;
		break;
	    }
	  case INSN_OP_PPADDR:		/* 93 */
	    {
		strconst arg;
		BGET_strconst(arg);
		BSET_op_ppaddr(PL_op->op_ppaddr, arg);
		break;
	    }
	  case INSN_OP_TARG:		/* 94 */
	    {
		PADOFFSET arg;
		BGET_PADOFFSET(arg);
		PL_op->op_targ = arg;
		break;
	    }
	  case INSN_OP_TYPE:		/* 95 */
	    {
		OPCODE arg;
		BGET_U16(arg);
		BSET_op_type(PL_op, arg);
		break;
	    }
	  case INSN_OP_OPT:		/* 96 */
	    {
		U8 arg;
		BGET_U8(arg);
		PL_op->op_opt = arg;
		break;
	    }
	  case INSN_OP_LATEFREE:		/* 97 */
	    {
		U8 arg;
		BGET_U8(arg);
		PL_op->op_latefree = arg;
		break;
	    }
	  case INSN_OP_LATEFREED:		/* 98 */
	    {
		U8 arg;
		BGET_U8(arg);
		PL_op->op_latefreed = arg;
		break;
	    }
	  case INSN_OP_ATTACHED:		/* 99 */
	    {
		U8 arg;
		BGET_U8(arg);
		PL_op->op_attached = arg;
		break;
	    }
	  case INSN_OP_FLAGS:		/* 100 */
	    {
		U8 arg;
		BGET_U8(arg);
		PL_op->op_flags = arg;
		break;
	    }
	  case INSN_OP_PRIVATE:		/* 101 */
	    {
		U8 arg;
		BGET_U8(arg);
		PL_op->op_private = arg;
		break;
	    }
	  case INSN_OP_FIRST:		/* 102 */
	    {
		opindex arg;
		BGET_opindex(arg);
		cUNOP->op_first = arg;
		break;
	    }
	  case INSN_OP_LAST:		/* 103 */
	    {
		opindex arg;
		BGET_opindex(arg);
		cBINOP->op_last = arg;
		break;
	    }
	  case INSN_OP_OTHER:		/* 104 */
	    {
		opindex arg;
		BGET_opindex(arg);
		cLOGOP->op_other = arg;
		break;
	    }
	  case INSN_OP_PMREPLROOT:		/* 105 */
	    {
		opindex arg;
		BGET_opindex(arg);
		(cPMOP->op_pmreplrootu).op_pmreplroot = arg;
		break;
	    }
	  case INSN_OP_PMREPLSTART:		/* 106 */
	    {
		opindex arg;
		BGET_opindex(arg);
		(cPMOP->op_pmstashstartu).op_pmreplstart = arg;
		break;
	    }
#ifdef USE_ITHREADS
	  case INSN_OP_PMSTASHPV:		/* 107 */
	    {
		pvindex arg;
		BGET_pvindex(arg);
		BSET_op_pmstashpv(cPMOP, arg);
		break;
	    }
	  case INSN_OP_PMREPLROOTPO:		/* 108 */
	    {
		PADOFFSET arg;
		BGET_PADOFFSET(arg);
		(cPMOP->op_pmreplrootu).op_pmreplroot = (OP*)arg;
		break;
	    }
#else
	  case INSN_OP_PMREPLROOTGV:		/* 109 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&((cPMOP->op_pmreplrootu).op_pmreplroot) = arg;
		break;
	    }
#endif
	  case INSN_PREGCOMP:		/* 110 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_pregcomp(PL_op, arg);
		break;
	    }
	  case INSN_OP_PMFLAGS:		/* 111 */
	    {
		U16 arg;
		BGET_U16(arg);
		cPMOP->op_pmflags = arg;
		break;
	    }
	  case INSN_OP_SV:		/* 112 */
	    {
		svindex arg;
		BGET_svindex(arg);
		cSVOP->op_sv = arg;
		break;
	    }
	  case INSN_OP_PADIX:		/* 113 */
	    {
		PADOFFSET arg;
		BGET_PADOFFSET(arg);
		cPADOP->op_padix = arg;
		break;
	    }
	  case INSN_OP_PV:		/* 114 */
	    {
		pvcontents arg;
		BGET_pvcontents(arg);
		cPVOP->op_pv = arg;
		break;
	    }
	  case INSN_OP_PV_TR:		/* 115 */
	    {
		op_tr_array arg;
		BGET_op_tr_array(arg);
		cPVOP->op_pv = arg;
		break;
	    }
	  case INSN_OP_REDOOP:		/* 116 */
	    {
		opindex arg;
		BGET_opindex(arg);
		cLOOP->op_redoop = arg;
		break;
	    }
	  case INSN_OP_NEXTOP:		/* 117 */
	    {
		opindex arg;
		BGET_opindex(arg);
		cLOOP->op_nextop = arg;
		break;
	    }
	  case INSN_OP_LASTOP:		/* 118 */
	    {
		opindex arg;
		BGET_opindex(arg);
		cLOOP->op_lastop = arg;
		break;
	    }
	  case INSN_COP_LABEL:		/* 119 */
	    {
		pvindex arg;
		BGET_pvindex(arg);
		cCOP->cop_label = arg;
		break;
	    }
	  case INSN_COP_STASHPV:		/* 120 */
	    {
		pvindex arg;
		BGET_pvindex(arg);
		BSET_cop_stashpv(cCOP, arg);
		break;
	    }
	  case INSN_COP_FILE:		/* 121 */
	    {
		pvindex arg;
		BGET_pvindex(arg);
		BSET_cop_file(cCOP, arg);
		break;
	    }
	  case INSN_COP_SEQ:		/* 122 */
	    {
		U32 arg;
		BGET_U32(arg);
		cCOP->cop_seq = arg;
		break;
	    }
	  case INSN_COP_LINE:		/* 123 */
	    {
		line_t arg;
		BGET_U32(arg);
		cCOP->cop_line = arg;
		break;
	    }
	  case INSN_COP_WARNINGS:		/* 124 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_cop_warnings(cCOP, arg);
		break;
	    }
	  case INSN_MAIN_START:		/* 125 */
	    {
		opindex arg;
		BGET_opindex(arg);
		PL_main_start = arg;
		break;
	    }
	  case INSN_MAIN_ROOT:		/* 126 */
	    {
		opindex arg;
		BGET_opindex(arg);
		PL_main_root = arg;
		break;
	    }
	  case INSN_MAIN_CV:		/* 127 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&PL_main_cv = arg;
		break;
	    }
	  case INSN_CURPAD:		/* 128 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_curpad(PL_curpad, arg);
		break;
	    }
	  case INSN_PUSH_BEGIN:		/* 129 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_push_begin(PL_beginav, arg);
		break;
	    }
	  case INSN_PUSH_INIT:		/* 130 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_push_init(PL_initav, arg);
		break;
	    }
	  case INSN_PUSH_END:		/* 131 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_push_end(PL_endav, arg);
		break;
	    }
	  case INSN_CURSTASH:		/* 132 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&PL_curstash = arg;
		break;
	    }
	  case INSN_DEFSTASH:		/* 133 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&PL_defstash = arg;
		break;
	    }
	  case INSN_DATA:		/* 134 */
	    {
		U8 arg;
		BGET_U8(arg);
		BSET_data(none, arg);
		break;
	    }
	  case INSN_INCAV:		/* 135 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&GvAV(PL_incgv) = arg;
		break;
	    }
	  case INSN_LOAD_GLOB:		/* 136 */
	    {
		svindex arg;
		BGET_svindex(arg);
		BSET_load_glob(none, arg);
		break;
	    }
#ifdef USE_ITHREADS
	  case INSN_REGEX_PADAV:		/* 137 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&PL_regex_padav = arg;
		break;
	    }
#endif
	  case INSN_DOWARN:		/* 138 */
	    {
		U8 arg;
		BGET_U8(arg);
		PL_dowarn = arg;
		break;
	    }
	  case INSN_COMPPAD_NAME:		/* 139 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&PL_comppad_name = arg;
		break;
	    }
	  case INSN_XGV_STASH:		/* 140 */
	    {
		svindex arg;
		BGET_svindex(arg);
		*(SV**)&GvSTASH(bstate->bs_sv) = arg;
		break;
	    }
	  case INSN_SIGNAL:		/* 141 */
	    {
		strconst arg;
		BGET_strconst(arg);
		BSET_signal(bstate->bs_sv, arg);
		break;
	    }
	  case INSN_FORMFEED:		/* 142 */
	    {
		svindex arg;
		BGET_svindex(arg);
		PL_formfeed = arg;
		break;
	    }
	    default:
	      Perl_croak(aTHX_ "Illegal bytecode instruction %d\n", insn);
	      /* NOTREACHED */
	  }
        }
    }
    return 0;
}

/* ex: set ro: */
