/* -*- buffer-read-only: t -*-
 *
 *      Copyright (c) 1996-1999 Malcolm Beattie
 *      Copyright (c) 2007 Yann Nicolas Dauphin (no code yet from clisp)
 *      Copyright (c) 2008 Reini Urban
 *
 *      You may distribute under the terms of either the GNU General Public
 *      License or the Artistic License, as specified in the README file.
 *
 */
/*
 * This file is autogenerated from jitcompiler.pl. Changes made here will be lost.
 */
int jit_getc(struct byteloader_fdata *);
int jit_read(struct byteloader_fdata *, char *, size_t, size_t);
int jitrun(pTHX_ register struct byteloader_state *);
/* ex: set ro: */
