# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 284 code points in Unicode Version 6.0.0 that match
# any of the following regular expression constructs:
# 
#         \p{Decomposition_Type=Square}
#         \p{Dt=Sqr}
#         \p{Is_Decomposition_Type=Square}
#         \p{Is_Dt=Sqr}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Dt: Square}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
3250		
32CC	32CF	# [4]
3300	3357	# [88]
3371	33DF	# [111]
33FF		
1F130	1F14F	# [32]
1F190		
1F200	1F202	# [3]
1F210	1F23A	# [43]
END
