# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the 4412 code points in Unicode Version 6.0.0 that match
# any of the following regular expression constructs:
# 
#         \p{Bidi_Class=Other_Neutral}
#         \p{Bc=ON}
#         \p{Is_Bidi_Class=Other_Neutral}
#         \p{Is_Bc=ON}
# 
# perluniprops.pod should be consulted for the syntax rules for any of these,
# including if adding or subtracting white space, underscore, and hyphen
# characters matters or doesn't matter, and other permissible syntactic
# variants.  Upper/lower case distinctions never matter.
# 
# A colon can be substituted for the equals sign, and anything to the left of
# the equals (or colon) can be combined with anything to the right.  Thus,
# for example,
#         \p{Is_Bc: Other_Neutral}
# is also valid.
# 
# The format of the lines of this file is: START\tSTOP\twhere START is the
# starting code point of the range, in hex; STOP is the ending point, or if
# omitted, the range has just one code point.  Numbers in comments in
# [brackets] indicate how many code points are in the range.

return <<'END';
0021	0022	# [2]
0026	002A	# [5]
003B	0040	# [6]
005B	0060	# [6]
007B	007E	# [4]
00A1		
00A6	00A9	# [4]
00AB	00AC	# [2]
00AE	00AF	# [2]
00B4		
00B6	00B8	# [3]
00BB	00BF	# [5]
00D7		
00F7		
02B9	02BA	# [2]
02C2	02CF	# [14]
02D2	02DF	# [14]
02E5	02ED	# [9]
02EF	02FF	# [17]
0374	0375	# [2]
037E		
0384	0385	# [2]
0387		
03F6		
058A		
0606	0607	# [2]
060E	060F	# [2]
06DE		
06E9		
07F6	07F9	# [4]
0BF3	0BF8	# [6]
0BFA		
0C78	0C7E	# [7]
0F3A	0F3D	# [4]
1390	1399	# [10]
1400		
169B	169C	# [2]
17F0	17F9	# [10]
1800	180A	# [11]
1940		
1944	1945	# [2]
19DE	19FF	# [34]
1FBD		
1FBF	1FC1	# [3]
1FCD	1FCF	# [3]
1FDD	1FDF	# [3]
1FED	1FEF	# [3]
1FFD	1FFE	# [2]
2010	2027	# [24]
2035	2043	# [15]
2045	205E	# [26]
207C	207E	# [3]
208C	208E	# [3]
2100	2101	# [2]
2103	2106	# [4]
2108	2109	# [2]
2114		
2116	2118	# [3]
211E	2123	# [6]
2125		
2127		
2129		
213A	213B	# [2]
2140	2144	# [5]
214A	214D	# [4]
2150	215F	# [16]
2189		
2190	2211	# [130]
2214	2335	# [290]
237B	2394	# [26]
2396	23F3	# [94]
2400	2426	# [39]
2440	244A	# [11]
2460	2487	# [40]
24EA	26AB	# [450]
26AD	26FF	# [83]
2701	27CA	# [202]
27CC		
27CE	27FF	# [50]
2900	2B4C	# [589]
2B50	2B59	# [10]
2CE5	2CEA	# [6]
2CF9	2CFF	# [7]
2E00	2E31	# [50]
2E80	2E99	# [26]
2E9B	2EF3	# [89]
2F00	2FD5	# [214]
2FF0	2FFB	# [12]
3001	3004	# [4]
3008	3020	# [25]
3030		
3036	3037	# [2]
303D	303F	# [3]
309B	309C	# [2]
30A0		
30FB		
31C0	31E3	# [36]
321D	321E	# [2]
3250	325F	# [16]
327C	327E	# [3]
32B1	32BF	# [15]
32CC	32CF	# [4]
3377	337A	# [4]
33DE	33DF	# [2]
33FF		
4DC0	4DFF	# [64]
A490	A4C6	# [55]
A60D	A60F	# [3]
A673		
A67E	A67F	# [2]
A700	A721	# [34]
A788		
A828	A82B	# [4]
A874	A877	# [4]
FD3E	FD3F	# [2]
FDFD		
FE10	FE19	# [10]
FE30	FE4F	# [32]
FE51		
FE54		
FE56	FE5E	# [9]
FE60	FE61	# [2]
FE64	FE66	# [3]
FE68		
FE6B		
FF01	FF02	# [2]
FF06	FF0A	# [5]
FF1B	FF20	# [6]
FF3B	FF40	# [6]
FF5B	FF65	# [11]
FFE2	FFE4	# [3]
FFE8	FFEE	# [7]
FFF9	FFFD	# [5]
10101		
10140	1018A	# [75]
10190	1019B	# [12]
1091F		
10B39	10B3F	# [7]
11052	11065	# [20]
1D200	1D241	# [66]
1D245		
1D300	1D356	# [87]
1D6DB		
1D715		
1D74F		
1D789		
1D7C3		
1F000	1F02B	# [44]
1F030	1F093	# [100]
1F0A0	1F0AE	# [15]
1F0B1	1F0BE	# [14]
1F0C1	1F0CF	# [15]
1F0D1	1F0DF	# [15]
1F300	1F320	# [33]
1F330	1F335	# [6]
1F337	1F37C	# [70]
1F380	1F393	# [20]
1F3A0	1F3C4	# [37]
1F3C6	1F3CA	# [5]
1F3E0	1F3F0	# [17]
1F400	1F43E	# [63]
1F440		
1F442	1F48B	# [74]
1F48D	1F4F7	# [107]
1F4F9	1F4FC	# [4]
1F500	1F523	# [36]
1F525	1F53D	# [25]
1F550	1F567	# [24]
1F5FB	1F5FF	# [5]
1F601	1F610	# [16]
1F612	1F614	# [3]
1F616		
1F618		
1F61A		
1F61C	1F61E	# [3]
1F620	1F625	# [6]
1F628	1F62B	# [4]
1F62D		
1F630	1F633	# [4]
1F635	1F640	# [12]
1F645	1F64F	# [11]
1F680	1F6C5	# [70]
1F700	1F773	# [116]
END
