# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the synonymous mappings:
#         East_Asian_Width(cp)
#         Ea(cp)
# 
# where 'cp' is one of the 312_301 code points in Unicode Version 6.0.0 for
# which the mapping is not to 'Neutral'.  Note that these mappings are not
# accessible through the Perl core directly.
# 
# For information about what this property really means, see:
# http://www.unicode.org/reports/tr44/
# 
# The format of the non-comment portions of the main body of lines of this
# file is: START\tSTOP\tMAPPING where START is the starting code point of the
# range, in hex; STOP is the ending point, or if omitted, the range has just
# one code point; MAPPING is what each code point between START and STOP maps
# to.  Numbers in comments in [brackets] indicate how many code points are in
# the range (omitted when the range is a single code point or if the mapping
# is to the null string).

# The name this swash is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$utf8::SwashInfo{'ToEa'}{'format'} = 's'; # string
$utf8::SwashInfo{'ToEa'}{'missing'} = 'Neutral';

return <<'END';
0020	007E	Na	# [95]
00A1		A
00A2	00A3	Na	# [2]
00A4		A
00A5	00A6	Na	# [2]
00A7	00A8	A	# [2]
00AA		A
00AC		Na
00AD	00AE	A	# [2]
00AF		Na
00B0	00B4	A	# [5]
00B6	00BA	A	# [5]
00BC	00BF	A	# [4]
00C6		A
00D0		A
00D7	00D8	A	# [2]
00DE	00E1	A	# [4]
00E6		A
00E8	00EA	A	# [3]
00EC	00ED	A	# [2]
00F0		A
00F2	00F3	A	# [2]
00F7	00FA	A	# [4]
00FC		A
00FE		A
0101		A
0111		A
0113		A
011B		A
0126	0127	A	# [2]
012B		A
0131	0133	A	# [3]
0138		A
013F	0142	A	# [4]
0144		A
0148	014B	A	# [4]
014D		A
0152	0153	A	# [2]
0166	0167	A	# [2]
016B		A
01CE		A
01D0		A
01D2		A
01D4		A
01D6		A
01D8		A
01DA		A
01DC		A
0251		A
0261		A
02C4		A
02C7		A
02C9	02CB	A	# [3]
02CD		A
02D0		A
02D8	02DB	A	# [4]
02DD		A
02DF		A
0300	036F	A	# [112]
0391	03A1	A	# [17]
03A3	03A9	A	# [7]
03B1	03C1	A	# [17]
03C3	03C9	A	# [7]
0401		A
0410	044F	A	# [64]
0451		A
1100	115F	W	# [96]
11A3	11A7	W	# [5]
11FA	11FF	W	# [6]
2010		A
2013	2016	A	# [4]
2018	2019	A	# [2]
201C	201D	A	# [2]
2020	2022	A	# [3]
2024	2027	A	# [4]
2030		A
2032	2033	A	# [2]
2035		A
203B		A
203E		A
2074		A
207F		A
2081	2084	A	# [4]
20A9		H
20AC		A
2103		A
2105		A
2109		A
2113		A
2116		A
2121	2122	A	# [2]
2126		A
212B		A
2153	2154	A	# [2]
215B	215E	A	# [4]
2160	216B	A	# [12]
2170	2179	A	# [10]
2189		A
2190	2199	A	# [10]
21B8	21B9	A	# [2]
21D2		A
21D4		A
21E7		A
2200		A
2202	2203	A	# [2]
2207	2208	A	# [2]
220B		A
220F		A
2211		A
2215		A
221A		A
221D	2220	A	# [4]
2223		A
2225		A
2227	222C	A	# [6]
222E		A
2234	2237	A	# [4]
223C	223D	A	# [2]
2248		A
224C		A
2252		A
2260	2261	A	# [2]
2264	2267	A	# [4]
226A	226B	A	# [2]
226E	226F	A	# [2]
2282	2283	A	# [2]
2286	2287	A	# [2]
2295		A
2299		A
22A5		A
22BF		A
2312		A
2329	232A	W	# [2]
2460	24E9	A	# [138]
24EB	254B	A	# [97]
2550	2573	A	# [36]
2580	258F	A	# [16]
2592	2595	A	# [4]
25A0	25A1	A	# [2]
25A3	25A9	A	# [7]
25B2	25B3	A	# [2]
25B6	25B7	A	# [2]
25BC	25BD	A	# [2]
25C0	25C1	A	# [2]
25C6	25C8	A	# [3]
25CB		A
25CE	25D1	A	# [4]
25E2	25E5	A	# [4]
25EF		A
2605	2606	A	# [2]
2609		A
260E	260F	A	# [2]
2614	2615	A	# [2]
261C		A
261E		A
2640		A
2642		A
2660	2661	A	# [2]
2663	2665	A	# [3]
2667	266A	A	# [4]
266C	266D	A	# [2]
266F		A
269E	269F	A	# [2]
26BE	26BF	A	# [2]
26C4	26CD	A	# [10]
26CF	26E1	A	# [19]
26E3		A
26E8	26FF	A	# [24]
273D		A
2757		A
2776	277F	A	# [10]
27E6	27ED	Na	# [8]
2985	2986	Na	# [2]
2B55	2B59	A	# [5]
2E80	2E99	W	# [26]
2E9B	2EF3	W	# [89]
2F00	2FD5	W	# [214]
2FF0	2FFB	W	# [12]
3000		F
3001	303E	W	# [62]
3041	3096	W	# [86]
3099	30FF	W	# [103]
3105	312D	W	# [41]
3131	318E	W	# [94]
3190	31BA	W	# [43]
31C0	31E3	W	# [36]
31F0	321E	W	# [47]
3220	3247	W	# [40]
3248	324F	A	# [8]
3250	32FE	W	# [175]
3300	4DBF	W	# [6848]
4E00	A48C	W	# [22_157]
A490	A4C6	W	# [55]
A960	A97C	W	# [29]
AC00	D7A3	W	# [11_172]
D7B0	D7C6	W	# [23]
D7CB	D7FB	W	# [49]
E000	F8FF	A	# [6400]
F900	FAFF	W	# [512]
FE00	FE0F	A	# [16]
FE10	FE19	W	# [10]
FE30	FE52	W	# [35]
FE54	FE66	W	# [19]
FE68	FE6B	W	# [4]
FF01	FF60	F	# [96]
FF61	FFBE	H	# [94]
FFC2	FFC7	H	# [6]
FFCA	FFCF	H	# [6]
FFD2	FFD7	H	# [6]
FFDA	FFDC	H	# [3]
FFE0	FFE6	F	# [7]
FFE8	FFEE	H	# [7]
FFFD		A
1B000	1B001	W	# [2]
1F100	1F10A	A	# [11]
1F110	1F12D	A	# [30]
1F130	1F169	A	# [58]
1F170	1F19A	A	# [43]
1F200	1F202	W	# [3]
1F210	1F23A	W	# [43]
1F240	1F248	W	# [9]
1F250	1F251	W	# [2]
20000	2FFFD	W	# [65_534]
30000	3FFFD	W	# [65_534]
E0100	E01EF	A	# [240]
F0000	FFFFD	A	# [65_534]
100000	10FFFD	A	# [65_534]
END
