# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the synonymous mappings:
#         NFC_Quick_Check(cp)
#         NFC_QC(cp)
# 
# where 'cp' is one of the 1221 code points in Unicode Version 6.0.0 for
# which the mapping is not to 'Yes'.  Note that these mappings are not
# accessible through the Perl core directly.
# 
# For information about what this property really means, see:
# http://www.unicode.org/reports/tr44/
# 
# The format of the non-comment portions of the main body of lines of this
# file is: START\tSTOP\tMAPPING where START is the starting code point of the
# range, in hex; STOP is the ending point, or if omitted, the range has just
# one code point; MAPPING is what each code point between START and STOP maps
# to.  Numbers in comments in [brackets] indicate how many code points are in
# the range (omitted when the range is a single code point or if the mapping
# is to the null string).

# The name this swash is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$utf8::SwashInfo{'ToNFCQC'}{'format'} = 's'; # string
$utf8::SwashInfo{'ToNFCQC'}{'missing'} = 'Yes';

return <<'END';
0300	0304	M	# [5]
0306	030C	M	# [7]
030F		M
0311		M
0313	0314	M	# [2]
031B		M
0323	0328	M	# [6]
032D	032E	M	# [2]
0330	0331	M	# [2]
0338		M
0340	0341	N	# [2]
0342		M
0343	0344	N	# [2]
0345		M
0374		N
037E		N
0387		N
0653	0655	M	# [3]
093C		M
0958	095F	N	# [8]
09BE		M
09D7		M
09DC	09DD	N	# [2]
09DF		N
0A33		N
0A36		N
0A59	0A5B	N	# [3]
0A5E		N
0B3E		M
0B56	0B57	M	# [2]
0B5C	0B5D	N	# [2]
0BBE		M
0BD7		M
0C56		M
0CC2		M
0CD5	0CD6	M	# [2]
0D3E		M
0D57		M
0DCA		M
0DCF		M
0DDF		M
0F43		N
0F4D		N
0F52		N
0F57		N
0F5C		N
0F69		N
0F73		N
0F75	0F76	N	# [2]
0F78		N
0F81		N
0F93		N
0F9D		N
0FA2		N
0FA7		N
0FAC		N
0FB9		N
102E		M
1161	1175	M	# [21]
11A8	11C2	M	# [27]
1B35		M
1F71		N
1F73		N
1F75		N
1F77		N
1F79		N
1F7B		N
1F7D		N
1FBB		N
1FBE		N
1FC9		N
1FCB		N
1FD3		N
1FDB		N
1FE3		N
1FEB		N
1FEE	1FEF	N	# [2]
1FF9		N
1FFB		N
1FFD		N
2000	2001	N	# [2]
2126		N
212A	212B	N	# [2]
2329	232A	N	# [2]
2ADC		N
3099	309A	M	# [2]
F900	FA0D	N	# [270]
FA10		N
FA12		N
FA15	FA1E	N	# [10]
FA20		N
FA22		N
FA25	FA26	N	# [2]
FA2A	FA2D	N	# [4]
FA30	FA6D	N	# [62]
FA70	FAD9	N	# [106]
FB1D		N
FB1F		N
FB2A	FB36	N	# [13]
FB38	FB3C	N	# [5]
FB3E		N
FB40	FB41	N	# [2]
FB43	FB44	N	# [2]
FB46	FB4E	N	# [9]
110BA		M
1D15E	1D164	N	# [7]
1D1BB	1D1C0	N	# [6]
2F800	2FA1D	N	# [542]
END
