# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the synonymous mappings:
#         Numeric_Type(cp)
#         Nt(cp)
# 
# where 'cp' is one of the 1177 code points in Unicode Version 6.0.0 for
# which the mapping is not to 'None'.  Note that these mappings are not
# accessible through the Perl core directly.
# 
# For information about what this property really means, see:
# http://www.unicode.org/reports/tr44/
# 
# The format of the non-comment portions of the main body of lines of this
# file is: START\tSTOP\tMAPPING where START is the starting code point of the
# range, in hex; STOP is the ending point, or if omitted, the range has just
# one code point; MAPPING is what each code point between START and STOP maps
# to.  Numbers in comments in [brackets] indicate how many code points are in
# the range (omitted when the range is a single code point or if the mapping
# is to the null string).

# The name this swash is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$utf8::SwashInfo{'ToNt'}{'format'} = 's'; # string
$utf8::SwashInfo{'ToNt'}{'missing'} = 'None';

return <<'END';
0030	0039	Decimal # [10]
00B2	00B3	Digit	# [2]
00B9		Digit
00BC	00BE	Numeric # [3]
0660	0669	Decimal # [10]
06F0	06F9	Decimal # [10]
07C0	07C9	Decimal # [10]
0966	096F	Decimal # [10]
09E6	09EF	Decimal # [10]
09F4	09F9	Numeric # [6]
0A66	0A6F	Decimal # [10]
0AE6	0AEF	Decimal # [10]
0B66	0B6F	Decimal # [10]
0B72	0B77	Numeric # [6]
0BE6	0BEF	Decimal # [10]
0BF0	0BF2	Numeric # [3]
0C66	0C6F	Decimal # [10]
0C78	0C7E	Numeric # [7]
0CE6	0CEF	Decimal # [10]
0D66	0D6F	Decimal # [10]
0D70	0D75	Numeric # [6]
0E50	0E59	Decimal # [10]
0ED0	0ED9	Decimal # [10]
0F20	0F29	Decimal # [10]
0F2A	0F33	Numeric # [10]
1040	1049	Decimal # [10]
1090	1099	Decimal # [10]
1369	1371	Digit	# [9]
1372	137C	Numeric # [11]
16EE	16F0	Numeric # [3]
17E0	17E9	Decimal # [10]
17F0	17F9	Numeric # [10]
1810	1819	Decimal # [10]
1946	194F	Decimal # [10]
19D0	19D9	Decimal # [10]
19DA		Digit
1A80	1A89	Decimal # [10]
1A90	1A99	Decimal # [10]
1B50	1B59	Decimal # [10]
1BB0	1BB9	Decimal # [10]
1C40	1C49	Decimal # [10]
1C50	1C59	Decimal # [10]
2070		Digit
2074	2079	Digit	# [6]
2080	2089	Digit	# [10]
2150	2182	Numeric # [51]
2185	2189	Numeric # [5]
2460	2468	Digit	# [9]
2469	2473	Numeric # [11]
2474	247C	Digit	# [9]
247D	2487	Numeric # [11]
2488	2490	Digit	# [9]
2491	249B	Numeric # [11]
24EA		Digit
24EB	24F4	Numeric # [10]
24F5	24FD	Digit	# [9]
24FE		Numeric
24FF		Digit
2776	277E	Digit	# [9]
277F		Numeric
2780	2788	Digit	# [9]
2789		Numeric
278A	2792	Digit	# [9]
2793		Numeric
2CFD		Numeric
3007		Numeric
3021	3029	Numeric # [9]
3038	303A	Numeric # [3]
3192	3195	Numeric # [4]
3220	3229	Numeric # [10]
3251	325F	Numeric # [15]
3280	3289	Numeric # [10]
32B1	32BF	Numeric # [15]
3405		Numeric
3483		Numeric
382A		Numeric
3B4D		Numeric
4E00		Numeric
4E03		Numeric
4E07		Numeric
4E09		Numeric
4E5D		Numeric
4E8C		Numeric
4E94		Numeric
4E96		Numeric
4EBF	4EC0	Numeric # [2]
4EDF		Numeric
4EE8		Numeric
4F0D		Numeric
4F70		Numeric
5104		Numeric
5146		Numeric
5169		Numeric
516B		Numeric
516D		Numeric
5341		Numeric
5343	5345	Numeric # [3]
534C		Numeric
53C1	53C4	Numeric # [4]
56DB		Numeric
58F1		Numeric
58F9		Numeric
5E7A		Numeric
5EFE	5EFF	Numeric # [2]
5F0C	5F0E	Numeric # [3]
5F10		Numeric
62FE		Numeric
634C		Numeric
67D2		Numeric
6F06		Numeric
7396		Numeric
767E		Numeric
8086		Numeric
842C		Numeric
8CAE		Numeric
8CB3		Numeric
8D30		Numeric
9621		Numeric
9646		Numeric
964C		Numeric
9678		Numeric
96F6		Numeric
A620	A629	Decimal # [10]
A6E6	A6EF	Numeric # [10]
A830	A835	Numeric # [6]
A8D0	A8D9	Decimal # [10]
A900	A909	Decimal # [10]
A9D0	A9D9	Decimal # [10]
AA50	AA59	Decimal # [10]
ABF0	ABF9	Decimal # [10]
F96B		Numeric
F973		Numeric
F978		Numeric
F9B2		Numeric
F9D1		Numeric
F9D3		Numeric
F9FD		Numeric
FF10	FF19	Decimal # [10]
10107	10133	Numeric # [45]
10140	10178	Numeric # [57]
1018A		Numeric
10320	10323	Numeric # [4]
10341		Numeric
1034A		Numeric
103D1	103D5	Numeric # [5]
104A0	104A9	Decimal # [10]
10858	1085F	Numeric # [8]
10916	1091B	Numeric # [6]
10A40	10A43	Digit	# [4]
10A44	10A47	Numeric # [4]
10A7D	10A7E	Numeric # [2]
10B58	10B5F	Numeric # [8]
10B78	10B7F	Numeric # [8]
10E60	10E68	Digit	# [9]
10E69	10E7E	Numeric # [22]
11052	1105A	Digit	# [9]
1105B	11065	Numeric # [11]
11066	1106F	Decimal # [10]
12400	12431	Numeric # [50]
12434	12455	Numeric # [34]
12458	12462	Numeric # [11]
1D360	1D371	Numeric # [18]
1D7CE	1D7FF	Decimal # [50]
1F100	1F10A	Digit	# [11]
20001		Numeric
20064		Numeric
200E2		Numeric
20121		Numeric
2092A		Numeric
20983		Numeric
2098C		Numeric
2099C		Numeric
20AEA		Numeric
20AFD		Numeric
20B19		Numeric
22390		Numeric
22998		Numeric
23B1B		Numeric
2626D		Numeric
2F890		Numeric
END
