# !!!!!!!   DO NOT EDIT THIS FILE   !!!!!!!
# This file is machine-generated by lib/unicore/mktables from the Unicode
# database, Version 6.0.0.  Any changes made here will be lost!

# !!!!!!!   INTERNAL PERL USE ONLY   !!!!!!!
# This file is for internal use by the Perl program only.  The format and even
# the name or existence of this file are subject to change without notice.
# Don't use it directly.

# This file returns the synonymous mappings:
#         Word_Break(cp)
#         WB(cp)
# 
# where 'cp' is one of the 26_861 code points in Unicode Version 6.0.0 for
# which the mapping is not to 'Other'.  Note that these mappings are not
# accessible through the Perl core directly.
# 
# For information about what this property really means, see:
# http://www.unicode.org/reports/tr44/
# 
# The format of the non-comment portions of the main body of lines of this
# file is: START\tSTOP\tMAPPING where START is the starting code point of the
# range, in hex; STOP is the ending point, or if omitted, the range has just
# one code point; MAPPING is what each code point between START and STOP maps
# to.  Numbers in comments in [brackets] indicate how many code points are in
# the range (omitted when the range is a single code point or if the mapping
# is to the null string).

# The name this swash is to be known by, with the format of the mappings in
# the main body of the table, and what all code points missing from this file
# map to.
$utf8::SwashInfo{'ToWB'}{'format'} = 's'; # string
$utf8::SwashInfo{'ToWB'}{'missing'} = 'Other';

return <<'END';
000A		LF
000B	000C	Newline # [2]
000D		CR
0027		MidNumLet
002C		MidNum
002E		MidNumLet
0030	0039	Numeric # [10]
003A		MidLetter
003B		MidNum
0041	005A	ALetter # [26]
005F		ExtendNumLet
0061	007A	ALetter # [26]
0085		Newline
00AA		ALetter
00AD		Format
00B5		ALetter
00B7		MidLetter
00BA		ALetter
00C0	00D6	ALetter # [23]
00D8	00F6	ALetter # [31]
00F8	02C1	ALetter # [458]
02C6	02D1	ALetter # [12]
02E0	02E4	ALetter # [5]
02EC		ALetter
02EE		ALetter
0300	036F	Extend	# [112]
0370	0374	ALetter # [5]
0376	0377	ALetter # [2]
037A	037D	ALetter # [4]
037E		MidNum
0386		ALetter
0387		MidLetter
0388	038A	ALetter # [3]
038C		ALetter
038E	03A1	ALetter # [20]
03A3	03F5	ALetter # [83]
03F7	0481	ALetter # [139]
0483	0489	Extend	# [7]
048A	0527	ALetter # [158]
0531	0556	ALetter # [38]
0559		ALetter
0561	0587	ALetter # [39]
0589		MidNum
0591	05BD	Extend	# [45]
05BF		Extend
05C1	05C2	Extend	# [2]
05C4	05C5	Extend	# [2]
05C7		Extend
05D0	05EA	ALetter # [27]
05F0	05F3	ALetter # [4]
05F4		MidLetter
0600	0603	Format	# [4]
060C	060D	MidNum	# [2]
0610	061A	Extend	# [11]
0620	064A	ALetter # [43]
064B	065F	Extend	# [21]
0660	0669	Numeric # [10]
066B		Numeric
066C		MidNum
066E	066F	ALetter # [2]
0670		Extend
0671	06D3	ALetter # [99]
06D5		ALetter
06D6	06DC	Extend	# [7]
06DD		Format
06DF	06E4	Extend	# [6]
06E5	06E6	ALetter # [2]
06E7	06E8	Extend	# [2]
06EA	06ED	Extend	# [4]
06EE	06EF	ALetter # [2]
06F0	06F9	Numeric # [10]
06FA	06FC	ALetter # [3]
06FF		ALetter
070F		Format
0710		ALetter
0711		Extend
0712	072F	ALetter # [30]
0730	074A	Extend	# [27]
074D	07A5	ALetter # [89]
07A6	07B0	Extend	# [11]
07B1		ALetter
07C0	07C9	Numeric # [10]
07CA	07EA	ALetter # [33]
07EB	07F3	Extend	# [9]
07F4	07F5	ALetter # [2]
07F8		MidNum
07FA		ALetter
0800	0815	ALetter # [22]
0816	0819	Extend	# [4]
081A		ALetter
081B	0823	Extend	# [9]
0824		ALetter
0825	0827	Extend	# [3]
0828		ALetter
0829	082D	Extend	# [5]
0840	0858	ALetter # [25]
0859	085B	Extend	# [3]
0900	0903	Extend	# [4]
0904	0939	ALetter # [54]
093A	093C	Extend	# [3]
093D		ALetter
093E	094F	Extend	# [18]
0950		ALetter
0951	0957	Extend	# [7]
0958	0961	ALetter # [10]
0962	0963	Extend	# [2]
0966	096F	Numeric # [10]
0971	0977	ALetter # [7]
0979	097F	ALetter # [7]
0981	0983	Extend	# [3]
0985	098C	ALetter # [8]
098F	0990	ALetter # [2]
0993	09A8	ALetter # [22]
09AA	09B0	ALetter # [7]
09B2		ALetter
09B6	09B9	ALetter # [4]
09BC		Extend
09BD		ALetter
09BE	09C4	Extend	# [7]
09C7	09C8	Extend	# [2]
09CB	09CD	Extend	# [3]
09CE		ALetter
09D7		Extend
09DC	09DD	ALetter # [2]
09DF	09E1	ALetter # [3]
09E2	09E3	Extend	# [2]
09E6	09EF	Numeric # [10]
09F0	09F1	ALetter # [2]
0A01	0A03	Extend	# [3]
0A05	0A0A	ALetter # [6]
0A0F	0A10	ALetter # [2]
0A13	0A28	ALetter # [22]
0A2A	0A30	ALetter # [7]
0A32	0A33	ALetter # [2]
0A35	0A36	ALetter # [2]
0A38	0A39	ALetter # [2]
0A3C		Extend
0A3E	0A42	Extend	# [5]
0A47	0A48	Extend	# [2]
0A4B	0A4D	Extend	# [3]
0A51		Extend
0A59	0A5C	ALetter # [4]
0A5E		ALetter
0A66	0A6F	Numeric # [10]
0A70	0A71	Extend	# [2]
0A72	0A74	ALetter # [3]
0A75		Extend
0A81	0A83	Extend	# [3]
0A85	0A8D	ALetter # [9]
0A8F	0A91	ALetter # [3]
0A93	0AA8	ALetter # [22]
0AAA	0AB0	ALetter # [7]
0AB2	0AB3	ALetter # [2]
0AB5	0AB9	ALetter # [5]
0ABC		Extend
0ABD		ALetter
0ABE	0AC5	Extend	# [8]
0AC7	0AC9	Extend	# [3]
0ACB	0ACD	Extend	# [3]
0AD0		ALetter
0AE0	0AE1	ALetter # [2]
0AE2	0AE3	Extend	# [2]
0AE6	0AEF	Numeric # [10]
0B01	0B03	Extend	# [3]
0B05	0B0C	ALetter # [8]
0B0F	0B10	ALetter # [2]
0B13	0B28	ALetter # [22]
0B2A	0B30	ALetter # [7]
0B32	0B33	ALetter # [2]
0B35	0B39	ALetter # [5]
0B3C		Extend
0B3D		ALetter
0B3E	0B44	Extend	# [7]
0B47	0B48	Extend	# [2]
0B4B	0B4D	Extend	# [3]
0B56	0B57	Extend	# [2]
0B5C	0B5D	ALetter # [2]
0B5F	0B61	ALetter # [3]
0B62	0B63	Extend	# [2]
0B66	0B6F	Numeric # [10]
0B71		ALetter
0B82		Extend
0B83		ALetter
0B85	0B8A	ALetter # [6]
0B8E	0B90	ALetter # [3]
0B92	0B95	ALetter # [4]
0B99	0B9A	ALetter # [2]
0B9C		ALetter
0B9E	0B9F	ALetter # [2]
0BA3	0BA4	ALetter # [2]
0BA8	0BAA	ALetter # [3]
0BAE	0BB9	ALetter # [12]
0BBE	0BC2	Extend	# [5]
0BC6	0BC8	Extend	# [3]
0BCA	0BCD	Extend	# [4]
0BD0		ALetter
0BD7		Extend
0BE6	0BEF	Numeric # [10]
0C01	0C03	Extend	# [3]
0C05	0C0C	ALetter # [8]
0C0E	0C10	ALetter # [3]
0C12	0C28	ALetter # [23]
0C2A	0C33	ALetter # [10]
0C35	0C39	ALetter # [5]
0C3D		ALetter
0C3E	0C44	Extend	# [7]
0C46	0C48	Extend	# [3]
0C4A	0C4D	Extend	# [4]
0C55	0C56	Extend	# [2]
0C58	0C59	ALetter # [2]
0C60	0C61	ALetter # [2]
0C62	0C63	Extend	# [2]
0C66	0C6F	Numeric # [10]
0C82	0C83	Extend	# [2]
0C85	0C8C	ALetter # [8]
0C8E	0C90	ALetter # [3]
0C92	0CA8	ALetter # [23]
0CAA	0CB3	ALetter # [10]
0CB5	0CB9	ALetter # [5]
0CBC		Extend
0CBD		ALetter
0CBE	0CC4	Extend	# [7]
0CC6	0CC8	Extend	# [3]
0CCA	0CCD	Extend	# [4]
0CD5	0CD6	Extend	# [2]
0CDE		ALetter
0CE0	0CE1	ALetter # [2]
0CE2	0CE3	Extend	# [2]
0CE6	0CEF	Numeric # [10]
0CF1	0CF2	ALetter # [2]
0D02	0D03	Extend	# [2]
0D05	0D0C	ALetter # [8]
0D0E	0D10	ALetter # [3]
0D12	0D3A	ALetter # [41]
0D3D		ALetter
0D3E	0D44	Extend	# [7]
0D46	0D48	Extend	# [3]
0D4A	0D4D	Extend	# [4]
0D4E		ALetter
0D57		Extend
0D60	0D61	ALetter # [2]
0D62	0D63	Extend	# [2]
0D66	0D6F	Numeric # [10]
0D7A	0D7F	ALetter # [6]
0D82	0D83	Extend	# [2]
0D85	0D96	ALetter # [18]
0D9A	0DB1	ALetter # [24]
0DB3	0DBB	ALetter # [9]
0DBD		ALetter
0DC0	0DC6	ALetter # [7]
0DCA		Extend
0DCF	0DD4	Extend	# [6]
0DD6		Extend
0DD8	0DDF	Extend	# [8]
0DF2	0DF3	Extend	# [2]
0E31		Extend
0E34	0E3A	Extend	# [7]
0E47	0E4E	Extend	# [8]
0E50	0E59	Numeric # [10]
0EB1		Extend
0EB4	0EB9	Extend	# [6]
0EBB	0EBC	Extend	# [2]
0EC8	0ECD	Extend	# [6]
0ED0	0ED9	Numeric # [10]
0F00		ALetter
0F18	0F19	Extend	# [2]
0F20	0F29	Numeric # [10]
0F35		Extend
0F37		Extend
0F39		Extend
0F3E	0F3F	Extend	# [2]
0F40	0F47	ALetter # [8]
0F49	0F6C	ALetter # [36]
0F71	0F84	Extend	# [20]
0F86	0F87	Extend	# [2]
0F88	0F8C	ALetter # [5]
0F8D	0F97	Extend	# [11]
0F99	0FBC	Extend	# [36]
0FC6		Extend
102B	103E	Extend	# [20]
1040	1049	Numeric # [10]
1056	1059	Extend	# [4]
105E	1060	Extend	# [3]
1062	1064	Extend	# [3]
1067	106D	Extend	# [7]
1071	1074	Extend	# [4]
1082	108D	Extend	# [12]
108F		Extend
1090	1099	Numeric # [10]
109A	109D	Extend	# [4]
10A0	10C5	ALetter # [38]
10D0	10FA	ALetter # [43]
10FC		ALetter
1100	1248	ALetter # [329]
124A	124D	ALetter # [4]
1250	1256	ALetter # [7]
1258		ALetter
125A	125D	ALetter # [4]
1260	1288	ALetter # [41]
128A	128D	ALetter # [4]
1290	12B0	ALetter # [33]
12B2	12B5	ALetter # [4]
12B8	12BE	ALetter # [7]
12C0		ALetter
12C2	12C5	ALetter # [4]
12C8	12D6	ALetter # [15]
12D8	1310	ALetter # [57]
1312	1315	ALetter # [4]
1318	135A	ALetter # [67]
135D	135F	Extend	# [3]
1380	138F	ALetter # [16]
13A0	13F4	ALetter # [85]
1401	166C	ALetter # [620]
166F	167F	ALetter # [17]
1681	169A	ALetter # [26]
16A0	16EA	ALetter # [75]
16EE	16F0	ALetter # [3]
1700	170C	ALetter # [13]
170E	1711	ALetter # [4]
1712	1714	Extend	# [3]
1720	1731	ALetter # [18]
1732	1734	Extend	# [3]
1740	1751	ALetter # [18]
1752	1753	Extend	# [2]
1760	176C	ALetter # [13]
176E	1770	ALetter # [3]
1772	1773	Extend	# [2]
17B4	17B5	Format	# [2]
17B6	17D3	Extend	# [30]
17DD		Extend
17E0	17E9	Numeric # [10]
180B	180D	Extend	# [3]
1810	1819	Numeric # [10]
1820	1877	ALetter # [88]
1880	18A8	ALetter # [41]
18A9		Extend
18AA		ALetter
18B0	18F5	ALetter # [70]
1900	191C	ALetter # [29]
1920	192B	Extend	# [12]
1930	193B	Extend	# [12]
1946	194F	Numeric # [10]
19B0	19C0	Extend	# [17]
19C8	19C9	Extend	# [2]
19D0	19D9	Numeric # [10]
1A00	1A16	ALetter # [23]
1A17	1A1B	Extend	# [5]
1A55	1A5E	Extend	# [10]
1A60	1A7C	Extend	# [29]
1A7F		Extend
1A80	1A89	Numeric # [10]
1A90	1A99	Numeric # [10]
1B00	1B04	Extend	# [5]
1B05	1B33	ALetter # [47]
1B34	1B44	Extend	# [17]
1B45	1B4B	ALetter # [7]
1B50	1B59	Numeric # [10]
1B6B	1B73	Extend	# [9]
1B80	1B82	Extend	# [3]
1B83	1BA0	ALetter # [30]
1BA1	1BAA	Extend	# [10]
1BAE	1BAF	ALetter # [2]
1BB0	1BB9	Numeric # [10]
1BC0	1BE5	ALetter # [38]
1BE6	1BF3	Extend	# [14]
1C00	1C23	ALetter # [36]
1C24	1C37	Extend	# [20]
1C40	1C49	Numeric # [10]
1C4D	1C4F	ALetter # [3]
1C50	1C59	Numeric # [10]
1C5A	1C7D	ALetter # [36]
1CD0	1CD2	Extend	# [3]
1CD4	1CE8	Extend	# [21]
1CE9	1CEC	ALetter # [4]
1CED		Extend
1CEE	1CF1	ALetter # [4]
1CF2		Extend
1D00	1DBF	ALetter # [192]
1DC0	1DE6	Extend	# [39]
1DFC	1DFF	Extend	# [4]
1E00	1F15	ALetter # [278]
1F18	1F1D	ALetter # [6]
1F20	1F45	ALetter # [38]
1F48	1F4D	ALetter # [6]
1F50	1F57	ALetter # [8]
1F59		ALetter
1F5B		ALetter
1F5D		ALetter
1F5F	1F7D	ALetter # [31]
1F80	1FB4	ALetter # [53]
1FB6	1FBC	ALetter # [7]
1FBE		ALetter
1FC2	1FC4	ALetter # [3]
1FC6	1FCC	ALetter # [7]
1FD0	1FD3	ALetter # [4]
1FD6	1FDB	ALetter # [6]
1FE0	1FEC	ALetter # [13]
1FF2	1FF4	ALetter # [3]
1FF6	1FFC	ALetter # [7]
200C	200D	Extend	# [2]
200E	200F	Format	# [2]
2018	2019	MidNumLet # [2]
2024		MidNumLet
2027		MidLetter
2028	2029	Newline # [2]
202A	202E	Format	# [5]
203F	2040	ExtendNumLet # [2]
2044		MidNum
2054		ExtendNumLet
2060	2064	Format	# [5]
206A	206F	Format	# [6]
2071		ALetter
207F		ALetter
2090	209C	ALetter # [13]
20D0	20F0	Extend	# [33]
2102		ALetter
2107		ALetter
210A	2113	ALetter # [10]
2115		ALetter
2119	211D	ALetter # [5]
2124		ALetter
2126		ALetter
2128		ALetter
212A	212D	ALetter # [4]
212F	2139	ALetter # [11]
213C	213F	ALetter # [4]
2145	2149	ALetter # [5]
214E		ALetter
2160	2188	ALetter # [41]
24B6	24E9	ALetter # [52]
2C00	2C2E	ALetter # [47]
2C30	2C5E	ALetter # [47]
2C60	2CE4	ALetter # [133]
2CEB	2CEE	ALetter # [4]
2CEF	2CF1	Extend	# [3]
2D00	2D25	ALetter # [38]
2D30	2D65	ALetter # [54]
2D6F		ALetter
2D7F		Extend
2D80	2D96	ALetter # [23]
2DA0	2DA6	ALetter # [7]
2DA8	2DAE	ALetter # [7]
2DB0	2DB6	ALetter # [7]
2DB8	2DBE	ALetter # [7]
2DC0	2DC6	ALetter # [7]
2DC8	2DCE	ALetter # [7]
2DD0	2DD6	ALetter # [7]
2DD8	2DDE	ALetter # [7]
2DE0	2DFF	Extend	# [32]
2E2F		ALetter
3005		ALetter
302A	302F	Extend	# [6]
3031	3035	Katakana # [5]
303B	303C	ALetter # [2]
3099	309A	Extend	# [2]
309B	309C	Katakana # [2]
30A0	30FA	Katakana # [91]
30FC	30FF	Katakana # [4]
3105	312D	ALetter # [41]
3131	318E	ALetter # [94]
31A0	31BA	ALetter # [27]
31F0	31FF	Katakana # [16]
32D0	32FE	Katakana # [47]
3300	3357	Katakana # [88]
A000	A48C	ALetter # [1165]
A4D0	A4FD	ALetter # [46]
A500	A60C	ALetter # [269]
A610	A61F	ALetter # [16]
A620	A629	Numeric # [10]
A62A	A62B	ALetter # [2]
A640	A66E	ALetter # [47]
A66F	A672	Extend	# [4]
A67C	A67D	Extend	# [2]
A67F	A697	ALetter # [25]
A6A0	A6EF	ALetter # [80]
A6F0	A6F1	Extend	# [2]
A717	A71F	ALetter # [9]
A722	A788	ALetter # [103]
A78B	A78E	ALetter # [4]
A790	A791	ALetter # [2]
A7A0	A7A9	ALetter # [10]
A7FA	A801	ALetter # [8]
A802		Extend
A803	A805	ALetter # [3]
A806		Extend
A807	A80A	ALetter # [4]
A80B		Extend
A80C	A822	ALetter # [23]
A823	A827	Extend	# [5]
A840	A873	ALetter # [52]
A880	A881	Extend	# [2]
A882	A8B3	ALetter # [50]
A8B4	A8C4	Extend	# [17]
A8D0	A8D9	Numeric # [10]
A8E0	A8F1	Extend	# [18]
A8F2	A8F7	ALetter # [6]
A8FB		ALetter
A900	A909	Numeric # [10]
A90A	A925	ALetter # [28]
A926	A92D	Extend	# [8]
A930	A946	ALetter # [23]
A947	A953	Extend	# [13]
A960	A97C	ALetter # [29]
A980	A983	Extend	# [4]
A984	A9B2	ALetter # [47]
A9B3	A9C0	Extend	# [14]
A9CF		ALetter
A9D0	A9D9	Numeric # [10]
AA00	AA28	ALetter # [41]
AA29	AA36	Extend	# [14]
AA40	AA42	ALetter # [3]
AA43		Extend
AA44	AA4B	ALetter # [8]
AA4C	AA4D	Extend	# [2]
AA50	AA59	Numeric # [10]
AA7B		Extend
AAB0		Extend
AAB2	AAB4	Extend	# [3]
AAB7	AAB8	Extend	# [2]
AABE	AABF	Extend	# [2]
AAC1		Extend
AB01	AB06	ALetter # [6]
AB09	AB0E	ALetter # [6]
AB11	AB16	ALetter # [6]
AB20	AB26	ALetter # [7]
AB28	AB2E	ALetter # [7]
ABC0	ABE2	ALetter # [35]
ABE3	ABEA	Extend	# [8]
ABEC	ABED	Extend	# [2]
ABF0	ABF9	Numeric # [10]
AC00	D7A3	ALetter # [11_172]
D7B0	D7C6	ALetter # [23]
D7CB	D7FB	ALetter # [49]
FB00	FB06	ALetter # [7]
FB13	FB17	ALetter # [5]
FB1D		ALetter
FB1E		Extend
FB1F	FB28	ALetter # [10]
FB2A	FB36	ALetter # [13]
FB38	FB3C	ALetter # [5]
FB3E		ALetter
FB40	FB41	ALetter # [2]
FB43	FB44	ALetter # [2]
FB46	FBB1	ALetter # [108]
FBD3	FD3D	ALetter # [363]
FD50	FD8F	ALetter # [64]
FD92	FDC7	ALetter # [54]
FDF0	FDFB	ALetter # [12]
FE00	FE0F	Extend	# [16]
FE10		MidNum
FE13		MidLetter
FE14		MidNum
FE20	FE26	Extend	# [7]
FE33	FE34	ExtendNumLet # [2]
FE4D	FE4F	ExtendNumLet # [3]
FE50		MidNum
FE52		MidNumLet
FE54		MidNum
FE55		MidLetter
FE70	FE74	ALetter # [5]
FE76	FEFC	ALetter # [135]
FEFF		Format
FF07		MidNumLet
FF0C		MidNum
FF0E		MidNumLet
FF1A		MidLetter
FF1B		MidNum
FF21	FF3A	ALetter # [26]
FF3F		ExtendNumLet
FF41	FF5A	ALetter # [26]
FF66	FF9D	Katakana # [56]
FF9E	FF9F	Extend	# [2]
FFA0	FFBE	ALetter # [31]
FFC2	FFC7	ALetter # [6]
FFCA	FFCF	ALetter # [6]
FFD2	FFD7	ALetter # [6]
FFDA	FFDC	ALetter # [3]
FFF9	FFFB	Format	# [3]
10000	1000B	ALetter # [12]
1000D	10026	ALetter # [26]
10028	1003A	ALetter # [19]
1003C	1003D	ALetter # [2]
1003F	1004D	ALetter # [15]
10050	1005D	ALetter # [14]
10080	100FA	ALetter # [123]
10140	10174	ALetter # [53]
101FD		Extend
10280	1029C	ALetter # [29]
102A0	102D0	ALetter # [49]
10300	1031E	ALetter # [31]
10330	1034A	ALetter # [27]
10380	1039D	ALetter # [30]
103A0	103C3	ALetter # [36]
103C8	103CF	ALetter # [8]
103D1	103D5	ALetter # [5]
10400	1049D	ALetter # [158]
104A0	104A9	Numeric # [10]
10800	10805	ALetter # [6]
10808		ALetter
1080A	10835	ALetter # [44]
10837	10838	ALetter # [2]
1083C		ALetter
1083F	10855	ALetter # [23]
10900	10915	ALetter # [22]
10920	10939	ALetter # [26]
10A00		ALetter
10A01	10A03	Extend	# [3]
10A05	10A06	Extend	# [2]
10A0C	10A0F	Extend	# [4]
10A10	10A13	ALetter # [4]
10A15	10A17	ALetter # [3]
10A19	10A33	ALetter # [27]
10A38	10A3A	Extend	# [3]
10A3F		Extend
10A60	10A7C	ALetter # [29]
10B00	10B35	ALetter # [54]
10B40	10B55	ALetter # [22]
10B60	10B72	ALetter # [19]
10C00	10C48	ALetter # [73]
11000	11002	Extend	# [3]
11003	11037	ALetter # [53]
11038	11046	Extend	# [15]
11066	1106F	Numeric # [10]
11080	11082	Extend	# [3]
11083	110AF	ALetter # [45]
110B0	110BA	Extend	# [11]
110BD		Format
12000	1236E	ALetter # [879]
12400	12462	ALetter # [99]
13000	1342E	ALetter # [1071]
16800	16A38	ALetter # [569]
1B000		Katakana
1D165	1D169	Extend	# [5]
1D16D	1D172	Extend	# [6]
1D173	1D17A	Format	# [8]
1D17B	1D182	Extend	# [8]
1D185	1D18B	Extend	# [7]
1D1AA	1D1AD	Extend	# [4]
1D242	1D244	Extend	# [3]
1D400	1D454	ALetter # [85]
1D456	1D49C	ALetter # [71]
1D49E	1D49F	ALetter # [2]
1D4A2		ALetter
1D4A5	1D4A6	ALetter # [2]
1D4A9	1D4AC	ALetter # [4]
1D4AE	1D4B9	ALetter # [12]
1D4BB		ALetter
1D4BD	1D4C3	ALetter # [7]
1D4C5	1D505	ALetter # [65]
1D507	1D50A	ALetter # [4]
1D50D	1D514	ALetter # [8]
1D516	1D51C	ALetter # [7]
1D51E	1D539	ALetter # [28]
1D53B	1D53E	ALetter # [4]
1D540	1D544	ALetter # [5]
1D546		ALetter
1D54A	1D550	ALetter # [7]
1D552	1D6A5	ALetter # [340]
1D6A8	1D6C0	ALetter # [25]
1D6C2	1D6DA	ALetter # [25]
1D6DC	1D6FA	ALetter # [31]
1D6FC	1D714	ALetter # [25]
1D716	1D734	ALetter # [31]
1D736	1D74E	ALetter # [25]
1D750	1D76E	ALetter # [31]
1D770	1D788	ALetter # [25]
1D78A	1D7A8	ALetter # [31]
1D7AA	1D7C2	ALetter # [25]
1D7C4	1D7CB	ALetter # [8]
1D7CE	1D7FF	Numeric # [50]
E0001		Format
E0020	E007F	Format	# [96]
E0100	E01EF	Extend	# [240]
END
